### 主配置文件
# 项目相关配置
melon:
  #关闭
  switch: false
  # 名称
  name: @project.name@
  # 版本
  version: @melon.version@
  # 构建时间
  buildTime: @timestamp@
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置/apps/data/uploadPath，Linux配置 /apps/data/uploadPath）
  profile: /apps/data/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 配置管理
  conf:
    file-path: /apps/data/melon/confdata
    beat-time: 30

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /melon
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    # 请求头长度
    max-http-header-size: 8192
    threads:
      # tomcat最大线程数，默认为200
      max: 500
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 50


# Spring配置
spring:
  #应用名
  application:
    name: ${project.name}
  main:
    banner-mode: off
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    include: oauth
    active: @profiles.active@
  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    ssl: false
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 500MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

  activiti:
    database-schema-update: true
    # 自动部署验证设置:
    check-process-definitions: false
    process-definition-location-prefix: classpath:/bpmn/
    history-level: full
    async-executor-activate: false

# 日志配置
logging:
  level:
    fun.sssdnsy: debug
    org.springframework: warn


# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  # 不支持多包, 如有需要可在注解配置 或 提升扫包等级
  # 例如 com.**.**.mapper
  mapperPackage: fun.sssdnsy.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: fun.sssdnsy.domain
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  configuration:
    # 自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    # MyBatis 自动映射策略
    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
    autoMappingBehavior: PARTIAL
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: WARNING
    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志记录 (可单纯使用 p6spy 分析) org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 是否打印 Logo banner
    banner: false
    dbConfig:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      idType: ASSIGN_ID
      # 逻辑已删除值
      logicDeleteValue: 1
      # 逻辑未删除值
      logicNotDeleteValue: 0
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      # IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
      insertStrategy: NOT_NULL
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      updateStrategy: NOT_NULL
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy: NOT_NULL


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  banner: false

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# endpoints配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: xyzabcdefghijklmnopqrstuvw
  # 令牌有效期（默认30分钟）
  expireTime: 30

# Knife4j
knife4j:
  enable: true
  openapi:
    title: MELON文档
    description: "`MELON`API文档"
    email: sssdnsy@163.com
    concat: sssdnsy
    url: https://gitee.com/SSSDNSY
    version: @melon.version@
    license: GNU
    license-url: https://www.gnu.org/licenses/
    terms-of-service-url: http://127.0.0.1:8080/
    group:
      test1:
        group-name: @melon.version@
        api-rule: package
        api-rule-resources:
          - fun.sssdnsy.web.controller

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 分布式锁 lock4j 全局配置
lock4j:
  # 获取分布式锁超时时间，默认为 3000 毫秒
  acquire-timeout: 3000
  # 分布式锁的超时时间，默认为 30 秒
  expire: 30000

