server:
  port: 22222
  compression:
    enabled: false
    min-response-size: 1024
    mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png



spring:
  application:
    name: melon
  profiles:
    active: '@spring.profiles.active@'
  messages:
    basename: i18n/language
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-Pool
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 30
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      validation-timeout: 1000


application:
  banner:
    title: melon
    version: '@project.version@'
