server:
  port: 33333
  servlet:
    context-path: /melon

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?Unicode=true&characterEncoding=UTF-8
    username: root
    password: root_pwd
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

melon:
  conf:
    access-token: